### ISSUE TITLE
Can not repeat the performance

### ISSUE THREAD

**Issue by cogugoat** [TencentARC/AnimeSR#12]
Hi,

Thanks for providing this amazing projects. I tried the learning step 1, which trained 300k iterations with half of the provided AVC-Train datasets. Every setting in the **_train_animesr_step1_net_BasicOPonly.yml_** file was kept exactly the same. However, it appears to me the provided **_pretrained_animesr_step1_net_model.pth_** achieved much better performance than the model I trained (the 300k iteration is not done yet, I tried net_g_170000.pth). Would you mind shed some lights on the possible mistakes I might took. Thank you.

**Comment by ToTheBeginning** [comment]
Hi, first please check that you test it correctly, you can refer to this [similar issue](https://github.com/TencentARC/AnimeSR/issues/10#issuecomment-1458261619).

If it's not about checkpoint loading problem , please provide more details so we can help you. For example, when you say "much better performance", are you referring to perceptual visual quality or quantitative comparisons? Could you provide some examples? Also, did you use 4 GPUs to train the model, and what about 300k iteration and full datasets?

**Comment by cogugoat** [comment]
> Hi, first please check that you test it correctly, you can refer to this [similar issue](https://github.com/TencentARC/AnimeSR/issues/10#issuecomment-1458261619).
> 
> If it's not about checkpoint loading problem , please provide more details so we can help you. For example, when you say "much better performance", are you referring to perceptual visual quality or quantitative comparisons? Could you provide some examples? Also, did you use 4 GPUs to train the model, and what about 300k iteration and full datasets?

Thanks for the response. After checked the link, I did suffer from the same strict = True issue when load the model, and I guess no meaningful parameters has been loaded. I have two concerns about the generated step1 
 model. With step1, I got the pth file with size of 12M which is twice of the provided _**pretrained_animesr_step1_net_model.pth**_. In addition, I would like to know whether the provided opt files are specific to the AnimeSR_v2. In other words, I followed the exact training steps and no modification on opt yml file, but generated training pth file can not be directly loaded within scripts/inference_animesr_frames.py file. Thanks.

**Comment by cogugoat** [comment]
Thank you, I solved the problem by load with ['params']
