### ISSUE TITLE
dataset file corrupted

### ISSUE THREAD

**Issue by balancedbirds** [TencentARC/AnimeSR#3]
Hello! I'm glad to get the AVC dataset. However, I found thousands of pictures which are corrupted in AVC-Train. At first, I thought my PC has something wrong. So, I download the AVC dataset three times. But the same problem occurred every times. Is there bug in AVC-Train dataset?

**Comment by balancedbirds** [comment]
Hi, here is the log file of my bandizip. All 3830 error file is logged.





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "TencentARC/AnimeSR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月28日(星期三) 下午2:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [TencentARC/AnimeSR] dataset file corrupted (Issue #3)





 
Hi, can you provide more details (e.g., the clip name, image name, and the image itself) about the corrupted files, so we can check what's going wrong here?

**Comment by ToTheBeginning** [comment]
We didn't see your log file, can you send this log file with several image samples directly to yanzewu@tencent.com?

In the mean time, can you follow the steps below to see if you can extract successfully?

1. check the **md5sum** of the files.
    * AVC-Train-sub.zip: 2f8564f15f48b48bdec6fb2cfdf87703
              AVC-Train-sub.z01: 3f53b1ab022131edecc84d7795b145ee
              AVC-Train-sub.z02: 236e2bc130fc6045622886dc902439b0
              AVC-Train-sub.z03: 4edc262f3663d5660e8efd2812f4b249
              AVC-Train-sub.z04: ccfc0072e59141cdaa536621f3e0dd1f
              AVC-Train-sub.z05: a9772cf729598270062e657437a3c5c6
              AVC-Train-sub.z06: b2c35bc067e76b373786eba8987b1295
              AVC-Train-sub.z07: 6cb126a80440c7931f04441dfa38360f
              AVC-Train-sub.z08: 0498c0eaafa69550c89bf56851fb4533
              AVC-Train-sub.z09: 3ab6d427f2fd2ebb5e57ccb9b6e0f54c

2. using **zip** and **unzip** commands to extract the files.
    a. put all the sub zips into one folder
    b. run `zip AVC-Train-sub.zip -s=0 --out AVC-Train.zip`
    c. run `unzip AVC-Train.zip`

**Comment by balancedbirds** [comment]
I download the dataset again and get all 55300 pictures successfully!
Thanks very much for your help!
