### ISSUE TITLE
Code question

### ISSUE THREAD

**Issue by zdyshine** [TencentARC/AnimeSR#4]
Hi, Thanks for your wonderful work.
In https://github.com/TencentARC/AnimeSR/blob/main/animesr/data/ffmpeg_anime_dataset.py
line 103: img_bytes = self.file_client.get(img_gt_path, 'gt')  and 
line 130: ffmpeg.input('pipe:', format='rawvideo', pix_fmt='rgb24', s=f'{width}x{height}',
I have check the code, line 103 will read a image with 'bgr', but in line 130, pix_fmt='rgb24'.
Is this a mistake？

**Comment by ToTheBeginning** [comment]
Yes, that is a mistake, thanks for pointing out.

However, since the `pix_fmt` of encode(img2video) and decode(video2img) are the same, which means it won't change the format of frames, still bgr in and bgr out. So, current code still works.

**Comment by zdyshine** [comment]
Thanks for your reply
