### ISSUE TITLE
changing degradation settings

### ISSUE THREAD

**Issue by Zarxrax** [TencentARC/AnimeSR#6]
When I do step 1 of training, where can I modify the settings used for the classic basic operators (blur, noise, etc)?
Does this go in the options yaml file? Or do I need to modify one of the python files?

**Comment by ToTheBeginning** [comment]
Modify the [python files](https://github.com/TencentARC/AnimeSR/blob/main/animesr/data/ffmpeg_anime_dataset.py) to change the degradation process.
Modify the yaml file to change the hyper-parameters of the degradation range, such as noise sigma change.
